export type AccountType = 'aset' | 'liabilitas' | 'ekuitas' | 'pendapatan' | 'beban';

export type AccountSubType =
  | 'aset_lancar'
  | 'aset_tetap'
  | 'liabilitas_lancar'
  | 'liabilitas_jangka_panjang'
  | 'ekuitas_modal'
  | 'ekuitas_laba_ditahan'
  | 'pendapatan_usaha'
  | 'pendapatan_lain'
  | 'hpp'
  | 'beban_operasional'
  | 'beban_lain';

export interface Account {
  id: string;
  code: string;
  name: string;
  type: AccountType;
  subType: AccountSubType;
  normalBalance: 'debit' | 'kredit';
  description?: string;
  isSystem?: boolean;
  isActive: boolean;
}

export type ContactType = 'customer' | 'vendor' | 'keduanya';

export interface Contact {
  id: string;
  name: string;
  companyName?: string;
  type: ContactType;
  email?: string;
  phone?: string;
  address?: string;
  taxId?: string; // NPWP
  arBalance: number; // Piutang berjalan
  apBalance: number; // Hutang berjalan
  openBalanceAR?: number;
  openBalanceAP?: number;
  totalSales?: number;
  totalPurchases?: number;
  createdAt: string;
}

export interface Product {
  id: string;
  sku: string;
  name: string;
  category: string;
  unit: string; // Pcs, Box, Dus, Kg
  salePrice: number;
  sellingPrice?: number;
  avgCost: number; // Weighted Average Costing (Read-only generated by engine)
  qtyOnHand: number; // Read-only generated by engine
  minStockAlert: number;
  inventoryAccountId?: string; // Akun 1104 Persediaan Barang Dagang
  cogsAccountId?: string; // Akun 5101 Beban Pokok Penjualan (HPP)
  salesAccountId?: string; // Akun 4101 Pendapatan Penjualan
  barcode?: string;
  createdAt?: string;
}

export interface JournalLine {
  id: string;
  accountId: string;
  journalEntryId?: string;
  debit: number;
  kredit: number;
  memo?: string;
}

export type SourceType =
  | 'sales_invoice'
  | 'purchase_bill'
  | 'cash_transaction'
  | 'payment_received'
  | 'bill_payment'
  | 'inventory_adjustment'
  | 'depreciation_entry'
  | 'bank_reconciliation'
  | 'journal_manual'
  | 'payment_in'
  | 'payment_out'
  | 'manual'
  | string;

export interface JournalEntry {
  id: string;
  entryNumber: string; // e.g. JV-2026-001
  date: string; // YYYY-MM-DD
  description: string;
  sourceType: SourceType;
  sourceId?: string;
  lines: JournalLine[];
  totalDebit: number;
  totalKredit: number;
  isBalanced: boolean;
  isVoided?: boolean;
  createdBy: string;
  createdAt: string;
}

export interface SalesInvoiceItem {
  id?: string;
  productId: string;
  productName?: string;
  qty: number;
  unitPrice: number;
  subtotal: number;
  cogsAmount?: number;
  isTaxable?: boolean;
  taxAmount?: number;
}

export interface SalesInvoice {
  id: string;
  invoiceNumber: string;
  contactId: string;
  contactName: string;
  date: string;
  dueDate: string;
  items: SalesInvoiceItem[];
  subtotal: number;
  taxRate?: number; // 0.11 for 11% PPN
  taxAmount: number;
  total: number;
  paidAmount: number;
  remainingAmount: number;
  status: 'draft' | 'terkirim' | 'sebagian' | 'lunas' | 'void' | 'dibayar_sebagian' | 'belum_dibayar' | string;
  journalEntryId?: string;
  notes?: string;
  createdAt?: string;
}

export type Invoice = SalesInvoice;

export interface PurchaseBillItem {
  id?: string;
  productId: string;
  productName?: string;
  qty: number;
  unitCost: number;
  subtotal: number;
  isTaxable: boolean;
  taxAmount?: number;
}

export interface PurchaseBill {
  id: string;
  billNumber: string;
  contactId: string;
  contactName: string;
  date: string;
  dueDate: string;
  items: PurchaseBillItem[];
  subtotal: number;
  taxAmount: number;
  total: number;
  paidAmount: number;
  remainingAmount: number;
  status: 'draft' | 'terbit' | 'sebagian' | 'lunas' | 'void' | 'dibayar_sebagian' | 'belum_dibayar' | string;
  journalEntryId?: string;
  notes?: string;
  createdAt?: string;
}

export interface Payment {
  id: string;
  paymentNumber?: string;
  transactionNumber?: string;
  date: string;
  type: 'in' | 'out' | 'diterima' | 'keluar' | 'dibayar' | string;
  contactId?: string;
  contactName?: string;
  invoiceId?: string;
  billId?: string;
  purchaseBillId?: string;
  paymentMethod?: string;
  amount: number;
  paymentAccountId?: string;
  cashAccountId?: string;
  notes?: string;
  description?: string;
  createdAt: string;
}

export interface CashTransaction {
  id: string;
  txNumber?: string;
  transactionNumber?: string;
  date: string;
  type: 'masuk' | 'keluar';
  fromToAccountId?: string;
  oppositeAccountId?: string;
  cashAccountId?: string;
  contraAccountId?: string;
  amount: number;
  recipientOrPayer?: string;
  description?: string;
  category: string;
  notes?: string;
  journalEntryId?: string;
  createdAt?: string;
}

export interface StockMovement {
  id: string;
  productId: string;
  productName?: string;
  date: string;
  referenceType?: 'in' | 'out' | 'adjustment' | 'masuk' | 'keluar' | string;
  type?: 'in' | 'out' | 'adjustment' | 'masuk' | 'keluar' | string;
  sourceType?: string;
  sourceId?: string;
  referenceNumber?: string;
  sourceRefNumber?: string;
  qtyChange?: number;
  qty?: number;
  unitPrice?: number;
  unitCost?: number;
  newQtyOnHand?: number;
  newAvgCost?: number;
  runningBalanceQty?: number;
  runningBalanceValue?: number;
  totalValuation?: number;
  totalValue?: number;
  createdAt?: string;
}

export interface UserSession {
  id: string;
  name: string;
  email: string;
  role: 'admin' | 'staff';
  avatarUrl: string;
}

export interface FixedAsset {
  id: string;
  code: string;
  name: string;
  category: 'peralatan' | 'kendaraan' | 'bangunan' | 'elektronik';
  acquisitionDate: string;
  acquisitionCost: number;
  salvageValue: number;
  usefulLifeMonths: number;
  assetAccountId: string;
  accumulatedDeprAccountId: string;
  deprExpenseAccountId: string;
  accumulatedDepreciation: number;
  netBookValue: number;
  lastDepreciationDate?: string;
}

export interface BankStatementItem {
  id: string;
  date: string;
  description: string;
  amount: number;
  type: 'credit' | 'debit';
  isReconciled: boolean;
  matchedJournalId?: string;
  referenceNo?: string;
}

export interface ClosedPeriod {
  periodMonth: string; // YYYY-MM
  closedAt: string;
  closedBy: string;
  netIncome: number;
  totalRevenue: number;
  totalExpense: number;
  closingEntryId: string;
  certificateNumber: string;
}

